@Expensive.Api_HostAddress = http://localhost:44133
@rowguid = 83ACBDD1-8657-435A-AA7E-2FE643608F8

### Get all categories
GET {{Expensive.Api_HostAddress}}/api/categories
Accept: application/json

### get by parameter and value
GET {{Expensive.Api_HostAddress}}/api/categories/expression/Name/Hogar
Accept: application/json

### get like by parameter and value
GET {{Expensive.Api_HostAddress}}/api/categories/like/Name/su
Accept: application/json

###CRUD CATEGORIES
### Get All Categories
GET {{Expensive.Api_HostAddress}}/api/CategoriesCrud
Accept: application/json

### Get a Categories by Rowguid
GET {{Expensive.Api_HostAddress}}/api/CategoriesCrud/{{rowguid}}}
Accept: application/json

### Create a new Categories
POST {{Expensive.Api_HostAddress}}/api/CategoriesCrud
Accept: application/json
Content-type: application/json
{
    "Name": "nueva categoria",
    "Description": "descripcion de la nueva categoria",
    "Operation" : "INCOME"
}

### Create a new Categories
PUT {{Expensive.Api_HostAddress}}/api/CategoriesCrud
Accept: application/json
Content-type: application/json
{
    "Name": "Actualizada categoria",
    "Description": "descripcion de la Actualizada categoria",
    "Operation" : "Expensive"
    "Rowguid": "{{rowguid}}"
}

### JWTToken Generation
GET {{Expensive.Api_HostAddress}}/api/JwtToken/Generate
Accept: application/json
    
### JWTToken Proof
GET {{Expensive.Api_HostAddress}}/api/JwtToken/Proof
Accept: application/json

### JWTToken password
GET {{Expensive.Api_HostAddress}}/api/JwtToken/password
Accept: application/json

### JWTToken password
GET {{Expensive.Api_HostAddress}}/api/JwtToken/password

### JWTToken revealed

POST {{Expensive.Api_HostAddress}}/api/JwtToken/revealed
Accept: application/json
Content-type: application/json
{
  "HashedPassword": "$2a$10$I926KNeYnha8lKQWjR6Zv.l3/Dzd4n9cM6O9.F2j2g8T6Ekf8bnMy"
}
###

# @name generatetoken

GET {{Expensive.Api_HostAddress}}/api/JwtToken/Generate
Accept: application/json
 
###

GET {{Expensive.Api_HostAddress}}/api/JwtToken/Proof
Accept: application/json
Authorization: Bearer {{generatetoken.response.body.$.token}}

###


### Account Controller Login and Register
### Login user intro app and generate JWT Token
POST {{Expensive.Api_HostAddress}}/api/Account/Login
Accept: application/json
Content-type: application/json
{
    "UserName" : "holguin",
    "Password" : "jose@123A"
}

### Register
POST {{Expensive.Api_HostAddress}}/api/Account/Register
Accept: application/json
Content-type: application/json
{
    "FirtName" : "Hector Olguin",
    "LastName" : "Baez Martes",
    "Email" : "holguin@gmail.com",
    "UserName" : "holguin",
    "Password" : "jose@123A"
}

### ChangePassword
PUT {{Expensive.Api_HostAddress}}/api/Account/ChangePassword
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiaG9sZ3VpbiIsIm5pY2tuYW1lIjoiaG9sZ3VpbiIsImVtYWlsIjoiaG9sZ3VpbkBnbWFpbC5jb20iLCJyb2xlIjoiZ2VuZXJpYyIsImp0aSI6IjNmMjZjODI5LTMzOWUtNDk0Ni05MTM0LWM2MDk2ZDhiYzQ0YyIsImV4cCI6MTc0ODU0OTI4MywiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo0NDEzMyIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDQxMzMifQ.Enaq8qifjadnndeUO6KapzShU4BMg0wUvwmzBv5q44U
Content-type: application/json
{
    "UserName": "mjmataramos",
    "OldPassword" : "jose@123A",
    "NewPassord" : "R@m0$$@123456%%"
}